# Generated by Django 6.0.5 on 2026-06-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_esewa_ref_id_order_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('mistake', 'Ordered by mistake'), ('cheaper', 'Found cheaper elsewhere'), ('delivery', 'Delivery takes too long'), ('changed', 'Changed my mind'), ('payment', 'Payment issue'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
