# Generated by Django 4.2.30 on 2026-07-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_status_orderstatushistory'),
        ('orders', '0005_order_delivery_city_order_delivery_district_and_more'),
    ]

    operations = [
    ]
