# Generated by Django 6.0.5 on 2026-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_coupon_order_discount_amount_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'Not Required'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded')], default='NONE', max_length=20),
        ),
    ]
