# Generated by Django 6.0.5 on 2026-07-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_refund_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged product'), ('WRONG_ITEM', 'Wrong item received'), ('ORDERED_BY_MISTAKE', 'Ordered by mistake'), ('BETTER_PRICE', 'Found a better price'), ('DELAYED', 'Delivery taking too long'), ('CHANGED_MIND', 'Changed my mind'), ('OTHER', 'Other')], max_length=30)),
                ('other_reason', models.TextField(blank=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_holder', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=50)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='orders.order')),
            ],
        ),
    ]
