# Generated by Django 4.2.30 on 2026-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_refund_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_status',
        ),
        migrations.AddField(
            model_name='coupon',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='BUY_X_GET_Y type only: number of items the customer must buy.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('FIRST_ORDER', 'First Order Only'), ('MIN_QUANTITY', 'Minimum Quantity'), ('BUY_X_GET_Y', 'Buy X Get Y')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='coupon',
            name='get_discount_percent',
            field=models.PositiveIntegerField(default=100, help_text="BUY_X_GET_Y type only: discount % applied to the 'get' items. 100 = free."),
        ),
        migrations.AddField(
            model_name='coupon',
            name='get_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='BUY_X_GET_Y type only: number of additional items that get discounted.', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='MIN_QUANTITY type only: minimum total cart items required.', null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage or flat amount. Ignored for BUY_X_GET_Y (use get_discount_percent instead).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Setting this also marks the coupon as a limited-time offer for notification purposes.', null=True),
        ),
    ]
