# Generated by Django 4.2.30 on 2026-07-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_refund_status_coupon_buy_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NONE', 'No Refund'), ('PENDING', 'Refund Pending'), ('COMPLETED', 'Refund Completed'), ('REJECTED', 'Refund Rejected')], default='NONE', max_length=20),
        ),
    ]
