# Generated by Django 6.0.5 on 2026-07-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_refundrequest'),
        ('orders', '0010_order_refund_status'),
    ]

    operations = [
    ]
