# Generated by Django 6.0.5 on 2026-09-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
