# Generated by Django 6.0.5 on 2026-09-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount obtained from loyalty points.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_redeemed',
            field=models.PositiveIntegerField(default=0, help_text='Number of loyalty points redeemed for this order.'),
        ),
    ]
