# Generated by Django 6.0.5 on 2026-09-25 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltytransaction_unique_purchase_loyalty_transaction_per_order'),
        ('orders', '0013_order_loyalty_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='minimum_loyalty_tier',
            field=models.ForeignKey(blank=True, help_text='Minimum loyalty tier required to use this coupon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='loyalty.loyaltytier'),
        ),
    ]
