# Generated by Django 6.0.5 on 2026-09-25 15:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_coupon_minimum_loyalty_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Shipping discount provided by this coupon. Use 0 for no shipping discount. The discount cannot exceed the shipping fee.', max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), help_text='Shipping fee charged for this order.', max_digits=10),
        ),
    ]
