# Generated by Django 4.2.30 on 2026-09-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_coupon_shipping_fee_order_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_public',
            field=models.BooleanField(default=True, help_text='True = broadcast to every customer as a promotion (notification + email to everyone). False = a private, targeted coupon — e.g. a churn win-back offer — that should never be announced site-wide.'),
        ),
    ]
