# Generated by Django 4.2.30 on 2026-09-30 04:59
# Generated by Django 6.0.5 on 2026-09-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_is_hidden'),
        ('orders', '0016_coupon_is_public'),
    ]

    operations = [
    ]
