# Generated by Django 4.2.30 on 2026-09-29 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_merge_0013_order_is_hidden_0016_coupon_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_user',
            field=models.ForeignKey(blank=True, help_text='If set, ONLY this customer can use the coupon. Leave blank for a coupon anyone can use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_coupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
