# Generated by Django 4.2.30 on 2026-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='customer_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='customer_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 ⭐'), (2, '2 ⭐⭐'), (3, '3 ⭐⭐⭐'), (4, '4 ⭐⭐⭐⭐'), (5, '5 ⭐⭐⭐⭐⭐')], null=True),
        ),
    ]
