# Generated by Django 6.0.5 on 2026-05-17 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_alter_category_options_category_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
