# Generated by Django 4.2.30 on 2026-07-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number appears first in the brand strip. Set by admin.'),
        ),
    ]
