# Generated by Django 6.0.5 on 2026-07-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount_percentage_product_offer_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
