# Generated by Django 4.2.30 on 2026-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_login_device',
            field=models.CharField(blank=True, default='Mobile Phone', max_length=20),
        ),
    ]
