# Generated by Django 4.2.30 on 2026-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_preferred_login_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_devices',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
