# Generated by Django 4.2.30 on 2026-07-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_gender_user_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='If off, this user will not receive coupon/offer emails (they still get in-app notifications either way).'),
        ),
    ]
