# Generated by Django 6.0.5 on 2026-09-21 09:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_alter_order_payment_status'),
        ('products', '0011_remove_product_discount_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('minimum_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('early_access_hours', models.PositiveIntegerField(default=0)),
                ('exclusive_offers', models.BooleanField(default=False)),
                ('free_shipping', models.BooleanField(default=False)),
                ('support_priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['minimum_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('public_start', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('bonus_points', models.PositiveIntegerField(default=0)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_shipping', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_promotions', to='products.product')),
            ],
            options={
                'ordering': ['-public_start'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_points', models.PositiveIntegerField(default=0)),
                ('lifetime_points_earned', models.PositiveIntegerField(default=0)),
                ('lifetime_points_redeemed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL)),
                ('current_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='loyalty.loyaltytier')),
            ],
            options={
                'ordering': ['-lifetime_points_earned'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('FIRST_PURCHASE', 'First Purchase'), ('REVIEW', 'Review Reward'), ('REFERRAL', 'Referral'), ('BONUS', 'Bonus'), ('REDEMPTION', 'Redemption'), ('REFUND_REVERSAL', 'Refund Reversal'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=30)),
                ('points', models.IntegerField(validators=[django.core.validators.MinValueValidator(-1000000)])),
                ('balance_after', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.loyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPromotionAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_start', models.DateTimeField()),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_access', to='loyalty.loyaltypromotion')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_access', to='loyalty.loyaltytier')),
            ],
            options={
                'ordering': ['access_start'],
                'constraints': [models.UniqueConstraint(fields=('promotion', 'tier'), name='unique_promotion_tier_access')],
            },
        ),
    ]
