# Generated by Django 6.0.5 on 2026-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0012_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'PURCHASE')), fields=('order', 'transaction_type'), name='unique_purchase_loyalty_transaction_per_order'),
        ),
    ]
