# Generated by Django 6.0.5 on 2026-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_loyaltytransaction_unique_purchase_loyalty_transaction_per_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('FIRST_PURCHASE', 'First Purchase'), ('REVIEW', 'Review Reward'), ('REFERRAL', 'Referral'), ('BONUS', 'Bonus'), ('REDEMPTION', 'Redemption'), ('REFUND_REVERSAL', 'Refund Reversal'), ('REDEMPTION_REVERSAL', 'Redemption Reversal'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment')], max_length=30),
        ),
    ]
