# Generated by Django 6.0.5 on 2026-05-30 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('products', '0007_alter_brand_logo_alter_category_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='userevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('CLICK', 'Click'), ('CART', 'Cart'), ('REMOVE_CART', 'Remove Cart'), ('WISHLIST', 'Wishlist'), ('ORDER', 'Order')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to='products.product'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'event_type'], name='activity_us_user_id_a19b47_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['user', 'created_at'], name='activity_us_user_id_10512b_idx'),
        ),
        migrations.AddIndex(
            model_name='userevent',
            index=models.Index(fields=['product', 'event_type'], name='activity_us_product_ef48ca_idx'),
        ),
    ]
