# Generated by Django 6.0.5 on 2026-05-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_userevent_options_alter_userevent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'Product View'), ('CLICK', 'Product Click'), ('CART', 'Add To Cart'), ('REMOVE_CART', 'Remove From Cart'), ('WISHLIST', 'Wishlist'), ('CHECKOUT_STARTED', 'Checkout Started'), ('ORDER', 'Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('PAYMENT_FAILED', 'Payment Failed'), ('REVIEW', 'Review')], db_index=True, max_length=30),
        ),
    ]
