# Generated by Django 6.0.5 on 2026-06-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_alter_userevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'Product View'), ('CLICK', 'Product Click'), ('CART', 'Add To Cart'), ('REMOVE_CART', 'Remove From Cart'), ('WISHLIST', 'Add To Wishlist'), ('REMOVE_WISHLIST', 'Remove From Wishlist'), ('CHECKOUT_STARTED', 'Checkout Started'), ('CART_ABANDONED', 'Cart Abandoned'), ('PAYMENT_STARTED', 'Payment Started'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('ORDER', 'Order Placed'), ('ORDER_CANCELLED', 'Order Cancelled'), ('REVIEW', 'Review')], db_index=True, max_length=30),
        ),
    ]
