# Generated by Django 6.0.5 on 2026-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('COUPON', 'New Coupon'), ('OFFER_EXPIRING', 'Offer Expiring Soon'), ('REFUND', 'Refund Processed'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
    ]
