# Generated by Django 6.0.5 on 2026-09-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('COUPON', 'New Coupon'), ('OFFER_EXPIRING', 'Offer Expiring Soon'), ('REFUND', 'Refund Processed'), ('GENERAL', 'General'), ('POINTS_EARNED', 'Points Earned'), ('POINTS_REDEEMED', 'Points Redeemed'), ('POINTS_RESTORED', 'Points Restored'), ('TIER_UPGRADE', 'Tier Upgrade')], default='GENERAL', max_length=20),
        ),
    ]
