# Generated by Django 6.0.5 on 2026-05-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('prediction', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeatureSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_logins', models.IntegerField(default=0)),
                ('total_product_views', models.IntegerField(default=0)),
                ('total_product_clicks', models.IntegerField(default=0)),
                ('total_cart_adds', models.IntegerField(default=0)),
                ('total_cart_removes', models.IntegerField(default=0)),
                ('cart_abandonment_count', models.IntegerField(default=0)),
                ('total_wishlist_adds', models.IntegerField(default=0)),
                ('total_wishlist_removes', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('checkout_abandonment_count', models.IntegerField(default=0)),
                ('order_cancel_count', models.IntegerField(default=0)),
                ('payment_failed_count', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('review_count', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0)),
                ('days_since_last_login', models.IntegerField(default=999)),
                ('days_since_last_activity', models.IntegerField(default=999)),
                ('days_since_last_order', models.IntegerField(default=999)),
                ('click_to_view_rate', models.FloatField(default=0)),
                ('cart_to_view_rate', models.FloatField(default=0)),
                ('order_to_cart_rate', models.FloatField(default=0)),
                ('wishlist_remove_rate', models.FloatField(default=0)),
                ('churn_label', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feature_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
