# Generated by Django 4.2.30 on 2026-06-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0002_userfeaturesnapshot_churnprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churnscore',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High')], max_length=10),
        ),
    ]
