# Generated by Django 4.2.30 on 2026-09-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0003_alter_churnscore_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnscore',
            name='override_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
