# Generated by Django 4.2.30 on 2026-09-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn', '0004_churnscore_override_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='churnscore',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnscore',
            name='model_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnscore',
            name='top_factors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
