# Generated by Django 4.2.30 on 2026-09-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_notification_notif_type'),
        ('orders', '0017_merge_0013_order_is_hidden_0016_coupon_is_public'),
        ('churn', '0005_churnscore_features_churnscore_model_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_score', models.FloatField()),
                ('before_risk_level', models.CharField(max_length=10)),
                ('after_score', models.FloatField(blank=True, null=True)),
                ('after_risk_level', models.CharField(blank=True, max_length=10)),
                ('score_change', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('VIEWED', 'Viewed'), ('RECOVERED', 'Customer Returned'), ('EXPIRED', 'Expired / No Response')], default='SENT', max_length=20)),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending'), ('RISK_REDUCED', 'Recovered + Risk Reduced'), ('IMPROVED_STILL_HIGH', 'Returned but Still High Risk'), ('RETURNED_NO_IMPROVEMENT', 'Returned but Risk Did Not Improve'), ('EXPIRED', 'Expired / No Response')], default='PENDING', max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('rescored_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('used_campaign_coupon', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_campaigns', to='orders.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_campaigns', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_campaigns', to='notifications.notification')),
                ('recovered_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_recoveries', to='orders.order')),
                ('source_score', models.ForeignKey(blank=True, help_text='Saved churn score that triggered this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_retention_campaigns', to='churn.churnscore')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
